args: !!python/object:argparse.Namespace
  abundance_dim: 5
  alpha_min: 0.4
  arch_instance: res_mbconv
  batch_size: 32
  beta_end: 0.1
  beta_schedule: linear
  beta_start: 0.0
  channel_mult: 2
  channels: 162
  checkpoints: ./checkpoints/
  data_option: Synthetic_Variability
  data_path: /tsi/data_education/Ladjal/koublal/open-source/IDNet/DATA/synth_DC2/alldata_ex_DC2.mat
  data_path_extract: /tsi/data_education/Ladjal/koublal/open-source/IDNet/DATA/synth_DC2/extracted_bundles.mat
  debuglogger: false
  devices: '0'
  diff_steps: 100
  dim: -1
  dir_prior: 0.3
  dropout_rate: 0.1
  embedding_dimension: 128
  endmembers: endmembers_dim
  endmembers_dim: 5
  fix_seed: 123456
  gamma: 0.01
  gpu: 0
  groups_per_scale: 2
  hidden_size: 32
  input_dim: 1
  itr: 1
  kl_dirichlet: 0.01
  lambda1: 1.0
  learning_rate: 0.001
  loss_type: kl
  mult: 1
  n_componenet: 3
  num_channels_dec: 32
  num_channels_enc: 32
  num_latent_per_group: 8
  num_layers: 2
  num_postprocess_blocks: 1
  num_postprocess_cells: 2
  num_preprocess_blocks: 1
  num_preprocess_cells: 3
  num_workers: 0
  number_columns: 100
  number_rows: 100
  patience: 100
  percentage: 0.05
  psi: 0.5
  res_dist: false
  root_path: /tsi/data_education/Ladjal/koublal/open-source/NH_v2
  scale: 0.1
  score_hdim: 64
  score_hw: 32
  train_epochs: 100
  training_testiong: true
  use_dirichlet_mix: true
  use_gpu: false
  use_multi_gpu: true
  weight_decay: 0.02
  weight_diffusion: 0.001
  without_diffusion: true
