training_optim:
  # Type data
  data_opt: "Synthetic_Variability"
  batch_size: 32
  min_delta : 0.000001
  monitor_loss : "val_loss"
  max_epochs: 50
  patience: 10000
  batch_shuffle : False
  validation_flag: True
  num_workers : 18
  save_path : /tsi/data_education/Ladjal/koublal/open-source/IDNet/results/
  checkpoint: 
  checkpoint_ckpt : 
  optimizer_config:
    type: Adam
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.01
  